//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;
use serde::{Serialize, Deserialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "accounts_metadata")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub account_id: i64,
  pub balance: f64
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::accounts::Entity",
    from = "Column::AccountId",
    to = "super::accounts::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Account
}

impl Related<super::accounts::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Account.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
