//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;
use serde::{Serialize, Deserialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "wallets")]
pub struct Model {
  #[sea_orm(primary_key)]
  #[serde(skip_deserializing)]
  pub id: i64,
  pub name: String,
  pub currency: String,
  pub description : String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    has_many = "super::wallets_metadata::Entity",
    from = "Column::Id",
    to = "super::wallets_metadata::Column::WalletId",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  WalletMetadata,
}

impl Related<super::wallets_metadata::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::WalletMetadata.def()
  }
}


impl ActiveModelBehavior for ActiveModel {}
